FROM adoptopenjdk/openjdk11:alpine

RUN apk update && apk add bash

RUN mkdir -p /opt/app

ENV PROJECT_HOME /opt/app

COPY target/app.jar $PROJECT_HOME/app.jar

WORKDIR $PROJECT_HOME

EXPOSE 8080

CMD ["java", "-jar" ,"./app.jar"]