FROM node:17.6-alpine AS builder

WORKDIR /usr/src/app

COPY . .

RUN npm install --legacy-peer-deps && \
    npm run build --prod

FROM nginx
COPY --from=builder /usr/src/app/dist/up-test-plan-frontend-ang/ /usr/share/nginx/html/

COPY /nginx/nginx.conf  /etc/nginx/conf.d/default.conf

EXPOSE 80
EXPOSE 8443
# Startup command

CMD ["nginx", "-c", "/etc/nginx/nginx.conf",  "-g", "daemon off;"]